scheduler:
  name: scheduler
  image: "daskdev/dask"
  imageTag: "latest"
  replicas: 1
  component: "dask-scheduler"
  serviceType: "LoadBalancer"
  servicePort: 8786
  containerPort: 8786
  resources: {}
  limits:
    cpu: 2
    memory: 7.5G
  requests:
    cpu: 2
    memory: 7.5G

webUI:
  name: webui
  servicePort: 80
  containerPort: 8787

worker:
  name: worker
  image: "daskdev/dask"
  imageTag: "latest"
  replicas: 3
  component: "dask-worker"
  containerPort: 8081
  resources: {}
  limits:
    cpu: 1
    memory: 3.5G
  requests:
    cpu: 1
    memory: 3.5G
